### PR TITLE
Manage discord spoilers

### PR DESCRIPTION
**Pull request by Sorunome**
The existing code for `some {{spoiler}}` doesn't seem to be what discords markdown for this is.

As of the point of writing this they introduced `some ||spoiler||` with all kind of cases. Currently webbrowser discord just gobbles up the `|`, but android discord makes it a spoiler correctly.

This makes spoilers have the ability to have a custom callback, as, well, each environment may want to treat spoilers differently

### CODE REVIEW

**Comment by brussell98** [comment]
Markdown on all clients will eventually be consistent as features are developed, so callback handling is not needed. Also, the library should not have custom html tags, so please revert it to the original output with altered regex.

**Comment by Sorunome** [comment]
> Also, the library should not have custom html tags, so please revert it to the original output with altered regex.

I am confused what you mean by this. the `<spoiler>` stuff was just for easy visualisation, it could also be `:spoiler:`

**Comment by Sorunome** [comment]
it that case it won't be usable in systems that use a limited subset of html, as mentioned in #4

**Comment by brussell98** [comment]
I don't understand what you mean by that. The Pr must maintain consistency with the rest of the library and follow the standards used. It is not my intention to support clients that have rare use-cases such as not being able to use classes.

**Comment by Sorunome** [comment]
while i adapted it now we will have to fork it, sadly

**Comment by brussell98** [comment]
Due to the number of issues with this PR I've decided to just implement it myself

**Pull request closed without merging**
